In [13]:
import pandas as pd
import numpy as np

In [ ]:
dados = 'https://www.ispdados.rj.gov.br/Arquivos/BaseDPEvolucaoMensalCisp.csv'
df = pd.read_csv(dados, sep=';' , encoding='latin 1')

(df.head()) #Rertona as cinco primeiras linhas do DF
df.tail()

In [ ]:
df.tail() #Retorna as cinco últimas linhas do DF

In [ ]:
df_furto_celular_cisp = df.groupby('cisp')['furto_celular'].sum().reset_index() 
df_furto_celular_cisp

In [ ]:
df.info() #Retorna informações sobre o DataFrame, como o número de linhas, colunas, tipos de dados e quantidade de valores não nulos em cada coluna.

In [ ]:
df.describe() #Retorna as estatísticas descritivas do DataFrame, como média, desvio padrão, valores mínimos e máximos, entre outros.

In [20]:
df.shape #quantidade de linhas e colunas

(37314, 65)

In [ ]:
df.columns #nomes das colunas

In [ ]:
df.iloc[0:5]

In [ ]:
df.loc[df['munic'] == 'Rio de Janeiro'] #Retorna as linhas do DataFrame onde a coluna 'munic' é igual a 'Rio de Janeiro'

In [ ]:
df_2024 = df.loc[df['ano'] == 2024] #Retorna as linhas do DataFrame onde a coluna 'ano' é igual a 2024]
df_2024

In [ ]:
df_baixada_2020 = df.loc[(df['ano'] == 2020) & (df['regiao'] == 'Baixada Fluminense')] #Retorna as linhas do DataFrame onde a coluna 'ano' é igual a 2020 e a coluna 'regiao' é igual a 'Baixada Fluminense'
df_baixada_2020

In [ ]:
dados = np.array([12, 15, 17, 20, 22, 25, 28, 30, 35, 40])
q1 = np.percentile(dados, 25)
q2 = np.percentile(dados, 50)
q3 = np.percentile(dados, 75)
print(f'Primeiro quartil (Q1): {q1}')
print(f'Segundo quartil (Q2, Mediana): {q2}')
print(f'Terceiroquartil (Q3): {q3}')

In [ ]:
array_furto_celular = np.array(df_furto_celular_cisp['furto_celular'])
q1_furto_celular = np.percentile(array_furto_celular, 25)
q2_furto_celular = np.percentile(array_furto_celular, 50)
q3_furto_celular = np.percentile(array_furto_celular, 75)
media = np.mean(array_furto_celular)
mediana = np.median(array_furto_celular)
distancia = (media - mediana) / mediana
iqr = q3_furto_celular - q1_furto_celular
limite_superior = q3_furto_celular + (1.5 * iqr)
limite_inferior = q1_furto_celular - (1.5 * iqr)
print(f'Primeiro quartil (Q1): {q1_furto_celular}')
print(f'Segundo quartil (Q2, Mediana): {q2_furto_celular}')
print(f'Terceiroquartil (Q3): {q3_furto_celular}')
print(f'O valor da média é: {media}')
print(f'O valor da mediana é: {mediana}')
print(f'A distância entre a média e a mediana é: {distancia * 100}')
print(f'O limite superior para detecção de outliers é: {limite_superior}')
print(f'O limite inferior para detecção de outliers é: {limite_inferior}')

In [ ]:
 
outliers_cisp_furto_celular = df_furto_celular_cisp.loc[df_furto_celular_cisp['furto_celular'] >= limite_superior]

outliers_cisp_furto_celular = outliers_cisp_furto_celular.sort_values (by='furto_celular', ascending=False)

outliers_cisp_furto_celular

In [ ]:
df_capital = df[df['regiao'] == 'Capital'] 
df_veiculos_cisp = df_capital.groupby('cisp')[['furto_veiculos', 'roubo_veiculo']].sum().reset_index()
df_veiculos_cisp['total_veiculos'] = df_veiculos_cisp['furto_veiculos'] + df_veiculos_cisp['roubo_veiculo']
array_veiculos = np.array(df_veiculos_cisp['total_veiculos'])
q1_veiculos = np.percentile(array_veiculos, 25)
q3_veiculos = np.percentile(array_veiculos, 75)
iqr_veiculos = q3_veiculos - q1_veiculos
limite_superior_veiculos = q3_veiculos + (1.5 * iqr_veiculos)
outliers_veiculos_cisp = df_veiculos_cisp[df_veiculos_cisp['total_veiculos'] > limite_superior_veiculos].sort_values(by='total_veiculos', ascending=False)
outliers_veiculos_cisp

    cisp  furto_veiculos  roubo_veiculo  total_veiculos
23    27           11907          27543           39450

In [61]:
#lapso temporal
max_ano = max(df['ano'])

df_decada = df.loc[df['ano'] > max_ano - 10] #retorna os dados dos últimos 10 anos

df_decada

,cisp,mes,ano,mes_ano,aisp,risp,munic,mcirc,regiao,hom_doloso,...,cmba,ameaca,pessoas_desaparecidas,encontro_cadaver,encontro_ossada,pol_militares_mortos_serv,pol_civis_mortos_serv,registro_ocorrencias,fase,capital
22357,1,1,2017,2017m01,5,1,Rio de Janeiro,3304557,Capital,0,...,0.0,12,0,0,0,0,0,375,3,False
22358,4,1,2017,2017m01,5,1,Rio de Janeiro,3304557,Capital,1,...,1.0,20,2,1,0,0,0,630,3,False
22359,5,1,2017,2017m01,5,1,Rio de Janeiro,3304557,Capital,0,...,3.0,26,1,0,0,0,0,836,3,False
22360,6,1,2017,2017m01,4,1,Rio de Janeiro,3304557,Capital,1,...,0.0,18,2,0,0,0,0,482,3,False
22361,7,1,2017,2017m01,5,1,Rio de Janeiro,3304557,Capital,3,...,0.0,10,0,0,0,0,0,230,3,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37309,159,1,2026,2026m01,35,4,Cachoeiras de Macacu,3300803,Interior,1,...,0.0,37,1,0,0,0,0,157,2,False
37310,165,1,2026,2026m01,33,5,Mangaratiba,3302601,Interior,0,...,0.0,32,0,0,0,0,0,234,2,False
37311,166,1,2026,2026m01,33,5,Angra dos Reis,3300100,Interior,2,...,0.0,98,9,1,0,0,0,713,2,False
37312,167,1,2026,2026m01,43,5,Paraty,3303807,Interior,1,...,0.0,25,2,0,0,0,0,258,2,False
37313,168,1,2026,2026m01,28,5,Rio Claro,3304409,Interior,1,...,0.0,3,0,0,0,0,0,57,2,False